  
#---------------------------------------------------------------------#
#     SEER UI   for /*arrs                                            #
#---------------------------------------------------------------------#  

  overseerr:
    image: image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    volumes:
      - ./volumes/seerr/config:/app/config
    env_file:
      - ./services/seerr/seerr.env    
    ports:
      - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3   
    labels:
      - homepage.group=MEDIA
      - homepage.name=seerr
      - homepage.icon=seerr.png
      - homepage.href=http://${RASPBERRYPI_HOST_IP}:5055  
      - homepage.description= media grabber 
    networks:
      private_network:
        ipv4_address: 172.19.0.25 # internal address of overseer
    restart: unless-stopped